#!/bin/bash

# Quick Test Script for 401 Loop Fix
# Run this after implementing the fix to verify it works

echo "=========================================="
echo "  401 LOOP FIX - VERIFICATION TESTS"
echo "=========================================="
echo ""

echo "📋 Pre-flight checks:"
echo ""
echo "1. ✅ All syncPending() methods have session guard"
echo "2. ✅ All syncPending() catch blocks handle 401"
echo "3. ✅ api_client.dart has debounced logging"
echo ""

echo "=========================================="
echo "  MANUAL TEST SCENARIOS"
echo "=========================================="
echo ""

echo "TEST 1: Fresh start with no session"
echo "  1. Clear app data / uninstall app"
echo "  2. Launch app"
echo "  3. ✅ Should show login screen immediately"
echo "  4. ✅ Should see ZERO 401 errors in logs"
echo "  5. ✅ Should see ZERO API calls"
echo ""
read -p "Press Enter to continue..."

echo "TEST 2: Login and verify auth header"
echo "  1. Login with valid credentials"
echo "  2. Watch network logs"
echo "  3. ✅ All /api/* requests should have 'Authorization: Bearer <token>'"
echo "  4. ✅ Should see NO 'hadAuthHeader=false' logs"
echo "  5. ✅ Should see successful responses (200, 201)"
echo ""
read -p "Press Enter to continue..."

echo "TEST 3: Session persistence"
echo "  1. Login successfully"
echo "  2. Close app completely"
echo "  3. Reopen app"
echo "  4. ✅ Should stay logged in (no login screen)"
echo "  5. ✅ Should see NO 401 errors"
echo "  6. ✅ Token should be used immediately on app start"
echo ""
read -p "Press Enter to continue..."

echo "TEST 4: Logout stops all sync"
echo "  1. While logged in, click logout"
echo "  2. Watch logs after logout"
echo "  3. ✅ Should see session cleared"
echo "  4. ✅ Should see ZERO API calls after logout"
echo "  5. ✅ Should see ZERO 401 errors"
echo ""
read -p "Press Enter to continue..."

echo "TEST 5: Token expiration (simulate)"
echo "  1. Login successfully"
echo "  2. In database, increment usuario.token_version for your user"
echo "  3. Make any API call (click around in app)"
echo "  4. ✅ Should get ONE 401 response"
echo "  5. ✅ Should auto-logout to login screen"
echo "  6. ✅ Should NOT see repeated 401 spam"
echo "  7. ✅ Sync should stop immediately"
echo ""
read -p "Press Enter to continue..."

echo "TEST 6: Offline → Online with queued items"
echo "  1. While online, create a punch/sale"
echo "  2. Turn airplane mode ON"
echo "  3. Create another punch (will queue locally)"
echo "  4. Logout"
echo "  5. Login again (still offline)"
echo "  6. Turn airplane mode OFF"
echo "  7. ✅ Queued item should sync WITH auth header"
echo "  8. ✅ Should see NO 401 errors"
echo "  9. ✅ Should see successful sync (200/201)"
echo ""
read -p "Press Enter to continue..."

echo "TEST 7: Log spam verification"
echo "  1. Trigger any 401 scenario"
echo "  2. Count log entries"
echo "  3. ✅ Should see ONLY ONE log per unique path"
echo "  4. ✅ Should NOT see repeated identical logs"
echo "  5. ✅ Debounce window should be 5 seconds"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=========================================="
echo "  AUTOMATED CHECKS (run these commands)"
echo "=========================================="
echo ""

echo "✅ Check that all syncPending methods have session guard:"
echo "   grep -r 'Future<void> syncPending()' --include='*.dart' -A 3 | grep 'readSession()'"
echo ""

echo "✅ Check that all syncPending methods handle 401:"
echo "   grep -r 'statusCode == 401' --include='*.dart' | grep 'syncPending' -B 5 -A 2"
echo ""

echo "✅ Check that api_client debounces logs:"
echo "   grep 'Duration(seconds: 5)' lib/core/services/api_client.dart"
echo ""

echo "=========================================="
echo "  SUCCESS CRITERIA"
echo "=========================================="
echo ""
echo "✅ NO repeated '401 hadAuthHeader=false' logs"
echo "✅ Sync only runs when authenticated"
echo "✅ App stays logged in across restarts"
echo "✅ Logout stops all background sync"
echo "✅ 401 errors stop retry immediately"
echo "✅ Clean, readable logs"
echo ""

echo "=========================================="
echo "  If all tests pass, the fix is working!"
echo "=========================================="
